### ISSUE TITLE
jest not work

### ISSUE THREAD

**Issue by chenbojian** [jenniferkaplannyc/jest_react_redux_node_webpack_complex_example#1]
> jest

 FAIL  reactTests/tests/teamAmerica.test.js
  ● Test suite failed to run

    Cannot find module 'react/lib/ReactComponentTreeHook' from 'ReactDebugTool.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (node_modules/react-test-renderer/lib/ReactDebugTool.js:16:30)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.106s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

**Comment by jenniferabowd** [comment]
@chenbojian Thank you so much for creating this issue ticket! I fixed the error. Turns out the issue was when I upgraded to React 16, I also needed to update my react-test-renderer. I found the solution to this [here](https://stackoverflow.com/questions/44680414/cannot-find-module-react-lib-reactcomponenttreehook-from-reactdebugtool-js/). Please let me know if you need any other help!
